### ISSUE TITLE
Collapsing comments is impossible with the extension enabled

### ISSUE THREAD

**Issue by GrandUpheaval** [Fubs/reddit-uncensored#1]
First of all I would like to say this has been a really useful extension! The one issue I have is that I can't collapse comments while I have it enabled. When I click to collapse a comment it immediately reverts to how it was.

**Comment by Fubs** [comment]
I know what you are referring to. I noticed that behavior as well while I was testing the extension, but I thought I had fixed it in the latest release version on the chrome/firefox extension stores. Are you using a chrome-based browser or firefox? Also, could you try toggling the "Expand all collapsed comments" setting on the extension options page and see if that affects the behavior? 

To open the extension options page in firefox, open the add-ons manager, click the three-dots next to the toggle switch, and click "Preferences". For chrome, open the chrome://extensions page, click on "Details" for the extension, and then click "Extension options".

**Comment by Fubs** [comment]
Should be fixed now. The updated version is live on the Firefox web store, and for Chrome it will be available as soon as they approve it (usually takes them a day or two).

**Comment by DannieBGoode** [comment]
This still happens in version 1.2.2 in Firefox, I had to turn off the `Expand all collapsed comments` option and now I can collapse comments, however it would be nicer if I could have this option enabled to expand all comments on page load and then be able to collapse comments as I please.

**Comment by Fubs** [comment]
Just tested this again and you're right. It seems that deleted comments will stay collapsed, but non-deleted comments are still being forcefully reopened. I'll try to fix this sometime today or tomorrow.

**Comment by Fubs** [comment]
@DannieBGoode Ok *now* it should be fixed. I uploaded the new version to firefox and chrome web stores.

**Comment by DannieBGoode** [comment]
> [@DannieBGoode](https://github.com/DannieBGoode) Ok _now_ it should be fixed. I uploaded the new version to firefox and chrome web stores.

It seems to work now! I'll have it in observation for a few days.

**Comment by DannieBGoode** [comment]
> > [@DannieBGoode](https://github.com/DannieBGoode) Ok _now_ it should be fixed. I uploaded the new version to firefox and chrome web stores.
> 
> It seems to work now! I'll have it in observation for a few days.

actually I was looking at it wrong, the new version hasn't still kicked in, I'll report back in a few days.

Thank you for the work.
